name:                kaletest
version:             0.1.0.0
github:              "tmciver/kaletest"
license:             BSD3
author:              "Tim McIver"
maintainer:          "tim@timmciver.com"
copyright:           "2017 Tim McIver"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/tmciver/kaletest#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  kaletest-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kaletest

tests:
  kaletest-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kaletest
